config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get 'questions/trending' => 'questions#trending', as: :trending
  get 'questions/voted' => 'questions#voted', as: :voted

  resources :users, only: [:new, :create]

  resources :sessions, only:[:create, :destroy]

  get 'login' => 'sessions#new'
  get 'logout'=> 'sessions#destroy'

  resources :questions do
    resources :answers, only: [:create, :destroy]
    resources :comments, only: [:new, :create]
    resources :votes, only: [:create, :update]
  end
  resources :answers do
    resources :comments, only:[:new, :create]
    resources :votes, only: [:create, :update]
  end

  resources :comments, only: [:new, :create] do
    resources :votes, only: [:create, :update]
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  include Voting
  belongs_to :user
  has_many :answers
  has_many :comments, :as => :commentable
  has_many :votes, :as => :votable

  def find_accepted_answer
    #maybe return nil rather than throwing error here
    self.answers.find_by(id: accepted_answer_id)
  end

  def self.most_recent_questions
    self.order(created_at: :desc).reverse
  end

  def self.trending_questions(limit=20)
    joins(:answers)
    .where('answers.created_at = (select max(created_at) from answers where question_id = questions.id)')
    .order('answers.created_at desc')
    .limit(limit)
  end

  def self.top_voted_questions
    joins("left join votes on votes.votable_id = questions.id \
            and votes.votable_type = 'Question'")
    .group('questions.id').order('sum(votes.value) desc')
  end

  private

  def self.questions_sorted_by_most_votes
    joins(:votes).group('questions.id').order('count(votes.votable_id) desc')
  end

  def self.questions_with_no_votes
    includes(:votes).where(votes: { :id => nil })
  end

end


# Users should be able to see questions sorted three ways: highest-voted, most recent, and "trending."

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :ensure_logged_in, only:[:new, :create, :update]
  def index
    @questions = Question.all
  end

  def trending
    @questions = Question.trending_questions
    render 'index'
  end

  def voted
    @questions = Question.top_voted_questions
    render 'index'
  end

  def new
    @question = Question.new
  end

  def create
    question = current_user.questions.build(question_params)
    if question.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = Answer.top_voted_answer(@question)
    @answer = Answer.new
    @comment = Comment.new
    @vote = Vote.new
  end

  def update
    question = Question.find(params[:id])
    question.update_attributes(accepted_answer_id: params[:chosen_answer_id])
    redirect_to question_path(question)
  end



private

  def question_params
    params.require(:question).permit(:title, :body)
  end

end

app/views/questions/index.html.erb
<h2>List of Questions</h2>

<div>
  <%= link_to "Ask a question", new_question_path %>
</div>


  <span><%= link_to "Trending", trending_path%>  <%= link_to "Highest Voted", voted_path %>  <%= link_to "Most Recent", questions_path %></span>
<ol>
  <% @questions.each do |question| %>
  <li><%=link_to question.title, question_path(question.id) %></li>
  <% end %>
</ol>

app/views/questions/new.html.erb
<H2>Ask a question</H2>

<%= form_for @question do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :body %>
  <%= f.text_area :body %>

  <%= f.submit %>
<% end %>

app/views/questions/show.html.erb
<div class="question_header" >
  <!--need to make show partial -->
  <h1><%=@question.title%></h1>
  <h3>Asked by: <%=@question.user.username%></h3>
  <h3><%=@question.body%></h3>
  <h4>Points:<%=@question.count_votes%></h4>
  <%= render :partial =>"votes/new", :controller => "votes", locals: {votable: @question} %>
  <% @question.comments.each do |comment| %>
  <div class="comments">
    <p><%=comment.body%></p>
    <h4>Points:<%=comment.count_votes%></h4>
    <%= render :partial =>"votes/new", :controller => "votes", locals: {votable: comment} %>
  </div>
  <% end %>

  <%= render :partial =>"comments/new", :controller => "comments", locals: {commentable: @question} %>
</div>

<div class="answer">
<%@answers.each do |a|%>
  <!--need to make show partial -->
  <div class="answer_header">
    <p><%=a.body%></p>
    <p>Answered by: <%=a.user.username%></p>
    <h4>Points:<%=a.count_votes%></h4>
    <%= render :partial =>"votes/new", :controller => "votes", locals: {votable: a} %>
    <%= render :partial =>"comments/new", :controller => "comments", locals: {commentable: a} %>
  </div>
  <div class="comments">
  <% a.comments.each do |comment| %>
    <p><%=comment.body%></p>
    <h4>Points:<%=comment.count_votes%></h4>
    <%= render :partial =>"votes/new", :controller => "votes", locals: {votable: comment} %>
  <% end %>
  </div>
  <%if current_user == @question.user %>
    <%= form_tag question_path, method: "put" do %>
      <%= hidden_field_tag "chosen_answer_id", a.id %>
      <%= submit_tag 'Pick This Answer' %>
    <% end %>
  <%end%>

<% end %>
</div>

<div>
  <%= form_for [@question, @answer] do |f|%>
    <%= f.label "Type Your Answer Here:" %>
    <%= f.text_area :body %>
    <%= f.submit "Submit Answer" %>
  <% end %>

  <div id="flash-container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, :class => "flash_#{name}" %>
      <% end %>
    <% end %>
  </div>
</div>