config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'

  get 'questions/trending' => 'questions#trending', as: :trending
  get 'questions/voted' => 'questions#voted', as: :voted

  resources :users, only: [:new, :create]

  resources :sessions, only:[:create, :destroy]

  get 'login' => 'sessions#new'
  get 'logout'=> 'sessions#destroy'

  resources :questions do
    resources :answers, only: [:create, :destroy]
    resources :comments, only: [:new, :create]
    resources :votes, only: [:create, :update]
  end
  resources :answers do
    resources :comments, only:[:new, :create]
    resources :votes, only: [:create, :update]
  end

  resources :comments, only: [:new, :create] do
    resources :votes, only: [:create, :update]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stack Overload</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>

</head>
<body>
  <nav>
    <ul>
        <center><h1><%= link_to "Welcome To StackOverload!", questions_path %></h1></center>

      <% if logged_in? %>
      <li><%= link_to 'Log out', logout_path %></li>
      <% else %>
      <li><%= link_to 'Join', new_user_path %></li>
      <li><%= link_to 'Log In', login_path %></li>
      <% end %>
    </ul>
  </nav>
  <div id="flash-container">
    <% flash.each do |name, msg| %>
      <% if msg.is_a?(String) %>
        <%= content_tag :div, msg, :class => "flash_#{name}" %>
      <% end %>
    <% end %>
  </div>

<%= yield %>

</body>
</html>